export const DEFAULT_JOURNALS = [
  "ESC heart failure",
  "JACC. Heart failure",
  "Journal of the American College of Cardiology",
  "Circulation",
  "European journal of heart failure",
  "JAMA cardiology",
  "Frontiers in cardiovascular medicine",
  "Journal of the American Heart Association",
  "Nature",
  "The Lancet",
  "The New England journal of medicine",
  "JAMA",
  "BMJ (Clinical research ed.)",
  "Annals of internal medicine",
  "European heart journal",
  "Circulation research",
  "Nature medicine",
  "The Lancet. Diabetes & endocrinology",
  "The Lancet. Oncology",
  "JAMA internal medicine",
  "JAMA oncology",
  "Science translational medicine",
  "Nature cardiovascular research"
]