// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkgrqknujcoxwdivyjda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrZ3Jxa251amNveHdkaXZ5amRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzODI2MjQsImV4cCI6MjA0OTk1ODYyNH0.S8RAwMQFOrbQAQDEPHKLsPIfZeMuuAJTwB8I9gZxwzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);